---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "oap75"
      - "olehmell"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "dependabot"
    pull-request-branch-name:
      separator: "/"